version: '3.8'

services:
  app:
    build: .
    ports:
      - "8556:8556"
    environment:
      - secret_key
      - FLASK_ENV
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWD
      - MXM_API
      - MXM_API2
      - REDIS_URL
      - SPOTIPY_CLIENT_ID
      - SPOTIPY_CLIENT_SECRET
      - FLASK_DEBUG
